/**
 * Generate HANDOFF.md — the documentation that ships with generated/.
 * Tells the downstream project what's in the box and how to use it.
 *
 * Reads config to produce accurate project-specific documentation.
 */
const fs = require('fs');
const path = require('path');

function generate(configs, registry, outputDir) {
  const { typography, standards, colors, effects } = configs;
  const defaultMode = colors['default-mode'] || 'dark';
  const headingFont = typography.families.heading;
  const bodyFont = typography.families.body;

  // Build component table
  const componentRows = Object.entries(registry).map(([name, def]) => {
    const el = def.selfClosing ? `<${def.element} />` : `<${def.element}>`;
    const attrs = def.htmlType.split('<')[0];
    const notes = [
      def.selfClosing ? 'Self-closing' : null,
      def.noInteractive ? 'No interactive states' : null,
      def.role ? `role="${def.role}"` : null,
    ].filter(Boolean).join(', ') || '—';
    return `| ${name}.tsx | \`${el}\` | \`${attrs}\` | ${def.textFamily} | ${notes} |`;
  });

  // Build text family table
  const familyRows = Object.entries(typography.textStyles).map(([family, def]) => {
    const sm = def.sm, md = def.md, lg = def.lg;
    return `| ${family} | ${def.font} | ${def.weight} | ${sm.size}/${sm['line-height']} | ${md.size}/${md['line-height']} | ${lg.size}/${lg['line-height']} |`;
  });

  // Check if shadows are flat
  const shadowsFlat = effects.shadow && Object.values(effects.shadow).every(v => v === 'none');

  const md = `# Design System Handoff

Generated by the Loom design system pipeline.

## Typography

**Fonts:** ${headingFont} (headings) / ${bodyFont} (body)
**Default mode:** ${defaultMode}

### Text Style Families

Components bind to a text style family. The \`size\` prop (sm/md/lg) selects the tier.
Use \`text-{family}-{size}\` classes in markup — these are real CSS classes, safe to interpolate.

| Family | Font | Weight | sm | md | lg |
|--------|------|--------|----|----|-----|
${familyRows.join('\n')}

### How it works in components

\`\`\`tsx
// Button uses "action" family — size flows through
<button className={\`text-action-\${size} \${sizeStyles[size]}\`}>

// In a molecule, every child scales together
<h3 className={\`text-title-\${size}\`}>{headline}</h3>
<p className={\`text-body-\${size}\`}>{excerpt}</p>
<Badge size={size}>Category</Badge>  {/* internally: text-label-\${size} */}
\`\`\`

## Token Architecture

\`\`\`
tokens.css                       ← plain CSS, portable
├── :root { }                    ← CSS custom properties (${defaultMode} mode values)
│   ├── Color palette primitives
│   ├── Semantic color roles
│   ├── Spacing scale + categories
│   ├── Sizing (radius, heights, icons, borders)
│   ├── Effects${shadowsFlat ? ' (shadows: none — flat style)' : ''}
│   ├── Typography font families
│   └── Z-index
└── [data-theme="${defaultMode === 'dark' ? 'light' : 'dark'}"] { }     ← Alternate mode overrides

loom.css                         ← plain CSS, portable
├── .text-{family}-{size} { }   ← Text style family classes (6 families × 3 tiers)
├── .interactive { }             ← Hover/active/focus/disabled states
└── @keyframes { }               ← Animation definitions

loom.components.css              ← plain CSS, portable; named component classes
└── .card / .badge / .button ...  ← shape only; compose with the classes above

loom.tailwind.css                ← Tailwind v4 only; a non-Tailwind build drops it silently
├── @utility { }                 ← Semantic spacing shorthands
└── @theme inline { }            ← Token vocabulary → Tailwind utilities
\`\`\`

## File Inventory

### tokens.css · loom.css · loom.components.css · loom.tailwind.css (DO NOT EDIT)
Regenerable from the Loom configs. Import in globals.css **in that order** — the bridge
reads what the first two define. Drop loom.tailwind.css and every token-derived utility
stops resolving without an error, because an unknown utility is not a build failure.

### components/ (YOURS TO MODIFY)
${componentRows.length} component scaffolds. Variant/size class maps are generated from config.

| File | Element | Attributes | Text Family | Notes |
|------|---------|------------|-------------|-------|
${componentRows.join('\n')}

### scaffold/
App-shell bootstrap files — \`init.sh\` wires the atom-agnostic shell into a Next.js project.

| File | Purpose |
|------|---------|
| \`init.sh <frontend-dir>\` | One-time: copies the shell + token substrate and installs core deps |
| \`globals.css\` | Tailwind + tokens import, base body styles, scrollbar, selection |
| \`ThemeProvider.tsx\` | React context for light/dark/system theme switching with localStorage persistence |
| \`layout.tsx\` | Root layout with ThemeProvider, Google Fonts, data-theme attribute |

## Setup

\`\`\`bash
# 1. App shell + substrate (once) — from the generated/ directory:
./scaffold/init.sh ./path-to-frontend

# 2. Picked atoms + token refresh (repeatable) — from the loom repo root:
npm run sync -- ./path-to-frontend     # reads loom-picks.json

# 3. Install the npm deps the sync reports, then:
cd ./path-to-frontend
npm run dev
\`\`\`

## Feedback Loop

| Situation | Action |
|-----------|--------|
| Token value is wrong | Edit the value in Loom's \`spec/config/\` → regenerate |
| Need a new component | Add to Loom's \`spec/config/components/\` → regenerate, or build from scratch |
| Component needs different structure | Modify directly (you own it) |
| Design system direction change | Re-run Loom's questionnaire → regenerate |
`;

  fs.writeFileSync(path.join(outputDir, 'HANDOFF.md'), md);
  console.log('  HANDOFF.md');
}

module.exports = { generate };
