/**
 * theme-init.js — the half of the theme mechanism that React cannot be.
 *
 * `ThemeProvider` reads localStorage in an effect and writes `data-theme` in a second
 * one. Both run after first paint, so on the first frame no attribute is set at all and
 * the page renders whatever `:root` says — the compiled-in default. A visitor who chose
 * the non-default mode sees one frame of the wrong theme on every load.
 *
 * That is not a React quirk to route around. Reading localStorage in a lazy `useState`
 * initializer would remove the effect and break server rendering, which is why the effect
 * is there. The effect is correct AND it is too late. Nothing rendered by React can set
 * an attribute before React has rendered.
 *
 * So this is a blocking classic script, inlined in `<head>` before the stylesheet's first
 * paint. No framework, no module, no imports — it has to run in a Vite index.html and a
 * Next document alike, and both of those are HTML rather than JSX.
 *
 * Worth knowing why it cannot be an external file: a `<script src>` without `defer` costs
 * a round trip before paint, and with `defer` it runs after it. Inline is the only form
 * that is both blocking and free, which is why this generates the TEXT a consumer pastes
 * rather than a module they import.
 *
 * It is generated rather than written into a README for one reason: it has to agree with
 * `theme-provider.tsx` about the storage key and the default mode, and two hand-kept
 * copies of a constant is how they stop agreeing. Both read THEME_STORAGE_KEY and the
 * project's `default-mode` from here.
 */

/** The localStorage key both halves read. One definition, two consumers. */
const THEME_STORAGE_KEY = 'theme';

/**
 * The snippet body, with no <script> wrapper — callers decide the wrapper, because a
 * Vite index.html wants `<script>…</script>` and a Next document wants a
 * dangerouslySetInnerHTML string.
 *
 * Deliberately small and defensive rather than clever:
 *
 * - try/catch around localStorage, because it throws rather than returning null in a
 *   private window with site data blocked. An exception here would run before the page
 *   renders, so an unguarded read is a blank page, not a wrong colour.
 * - It sets the attribute unconditionally, including for the default mode. Setting it
 *   only for the non-default leaves `[data-theme]` absent on a default load, which reads
 *   identically until a consumer writes a selector that expects the attribute to exist.
 * - `color-scheme` rides along. It is what tells the UA to paint form controls, the
 *   scrollbar gutter and the canvas to match, and Loom emits no `color-scheme` anywhere
 *   — so without this a dark app gets a light spinner in a date input.
 */
function buildThemeInit(configs) {
  const defaultMode = configs.colors['default-mode'] === 'light' ? 'light' : 'dark';

  return `/**
 * theme-init — paste the body of this file into an inline <script> in <head>, BEFORE
 * your stylesheet. Generated by Loom; do not edit here, and do not load it with a
 * <script src>: deferred it runs after first paint and undeferred it costs a round trip.
 *
 * Vite:  <script>…contents of this file…</script>   in index.html
 * Next:  <script dangerouslySetInnerHTML={{ __html: … }} />   in the document <head>
 *
 * Without it, ThemeProvider still works and still writes data-theme — one frame late, so
 * anyone who chose the non-default mode sees a flash of ${defaultMode} on every load.
 */
(function () {
  try {
    // Mirrors ThemeProvider's resolution exactly, and the theme-init-parity check
    // asserts that it does. Note what NOTHING STORED resolves to: the compiled-in
    // default, not the system preference. That is what the provider does, and making
    // this one smarter would mean a first-time visitor gets one theme before hydration
    // and another after — the flash this file exists to remove, reintroduced from the
    // other side. Whether the default should BE 'system' is a separate question about
    // the provider, not about this file.
    var stored = localStorage.getItem('${THEME_STORAGE_KEY}');
    var resolved =
      stored === 'light' || stored === 'dark'
        ? stored
        : stored === 'system'
          ? window.matchMedia('(prefers-color-scheme: dark)').matches
            ? 'dark'
            : 'light'
          : '${defaultMode}';
    document.documentElement.setAttribute('data-theme', resolved);
    document.documentElement.style.colorScheme = resolved;
  } catch (e) {
    // Storage blocked, or matchMedia missing. The default mode is already what :root
    // renders, so doing nothing is correct — never leave the page unstyled over a theme.
    document.documentElement.setAttribute('data-theme', '${defaultMode}');
  }
})();
`;
}

module.exports = { buildThemeInit, THEME_STORAGE_KEY };
