/**
 * Generated by Loom — do not edit. A resync overwrites this file.
 * Keep changes at the call site (className, a prop, a wrapper); those survive a resync.
 */
import { forwardRef, useEffect, useRef } from 'react';
import { cn } from './cn';
import { useFieldError } from './form-field';

type CheckboxProps = Omit<React.InputHTMLAttributes<HTMLInputElement>, 'type' | 'size'> & {
  size?: 'sm' | 'md' | 'lg';
  error?: boolean;
  /** Renders the mixed state. A DOM property, not an attribute — see below. */
  indeterminate?: boolean;
};

const Checkbox = forwardRef<HTMLInputElement, CheckboxProps>(
  ({ size = 'md', error, indeterminate = false, className, ...props }, ref) => {
    const hasError = useFieldError(error);
    const own = useRef<HTMLInputElement | null>(null);

    // The only reason this component is a file. indeterminate has no attribute and no
    // selector: it is settable on the element and nowhere else, so JSX cannot express it
    // and neither can the class layer.
    useEffect(() => {
      if (own.current) own.current.indeterminate = indeterminate;
    }, [indeterminate]);

    return (
      <input
        type="checkbox"
        ref={(node) => {
          own.current = node;
          if (typeof ref === 'function') ref(node);
          else if (ref) ref.current = node;
        }}
        className={cn('checkbox control', className)}
        data-size={size}
        aria-invalid={hasError || undefined}
        {...props}
      />
    );
  }
);
Checkbox.displayName = 'Checkbox';

export { Checkbox };
