/**
 * Generated by Loom — do not edit. A resync overwrites this file.
 * Keep changes at the call site (className, a prop, a wrapper); those survive a resync.
 */
import { type ClassValue, clsx } from 'clsx';

export function cn(...inputs: ClassValue[]) {
  return clsx(inputs);
}
