/**
 * Generated by Loom — do not edit. A resync overwrites this file.
 * Keep changes at the call site (className, a prop, a wrapper); those survive a resync.
 */
import { forwardRef } from 'react';
import { cn } from './cn';
import { useFieldError } from './form-field';

type RadioProps = Omit<React.InputHTMLAttributes<HTMLInputElement>, 'type' | 'size'> & {
  size?: 'sm' | 'md' | 'lg';
  error?: boolean;
};

const Radio = forwardRef<HTMLInputElement, RadioProps>(
  ({ size = 'md', error, className, ...props }, ref) => {
    const hasError = useFieldError(error);
    return (
      <input
        type="radio"
        ref={ref}
        className={cn('radio control', className)}
        data-size={size}
        aria-invalid={hasError || undefined}
        {...props}
      />
    );
  }
);
Radio.displayName = 'Radio';

export { Radio };
