/**
 * Generated by Loom — do not edit. A resync overwrites this file.
 * Keep changes at the call site (className, a prop, a wrapper); those survive a resync.
 */
import { forwardRef } from 'react';
import { cn } from './cn';
import { useFieldError } from './form-field';

type SwitchProps = Omit<React.InputHTMLAttributes<HTMLInputElement>, 'type' | 'size'> & {
  size?: 'sm' | 'md' | 'lg';
  error?: boolean;
};

const Switch = forwardRef<HTMLInputElement, SwitchProps>(
  ({ size = 'md', error, className, ...props }, ref) => {
    const hasError = useFieldError(error);
    return (
      // A checkbox underneath, because the behaviour is identical and the browser already
      // has it. role="switch" is what makes it announce as on/off rather than checked, and
      // it is the difference a hand-rolled one forgets.
      <input
        type="checkbox"
        role="switch"
        ref={ref}
        className={cn('switch control', className)}
        data-size={size}
        aria-invalid={hasError || undefined}
        {...props}
      />
    );
  }
);
Switch.displayName = 'Switch';

export { Switch };
