/**
 * theme-init — paste the body of this file into an inline <script> in <head>, BEFORE
 * your stylesheet. Generated by Loom; do not edit here, and do not load it with a
 * <script src>: deferred it runs after first paint and undeferred it costs a round trip.
 *
 * Vite:  <script>…contents of this file…</script>   in index.html
 * Next:  <script dangerouslySetInnerHTML={{ __html: … }} />   in the document <head>
 *
 * Without it, ThemeProvider still works and still writes data-theme — one frame late, so
 * anyone who chose the non-default mode sees a flash of dark on every load.
 */
(function () {
  try {
    // Mirrors ThemeProvider's resolution exactly, and the theme-init-parity check
    // asserts that it does. Note what NOTHING STORED resolves to: the compiled-in
    // default, not the system preference. That is what the provider does, and making
    // this one smarter would mean a first-time visitor gets one theme before hydration
    // and another after — the flash this file exists to remove, reintroduced from the
    // other side. Whether the default should BE 'system' is a separate question about
    // the provider, not about this file.
    var stored = localStorage.getItem('theme');
    var resolved =
      stored === 'light' || stored === 'dark'
        ? stored
        : stored === 'system'
          ? window.matchMedia('(prefers-color-scheme: dark)').matches
            ? 'dark'
            : 'light'
          : 'dark';
    document.documentElement.setAttribute('data-theme', resolved);
    document.documentElement.style.colorScheme = resolved;
  } catch (e) {
    // Storage blocked, or matchMedia missing. The default mode is already what :root
    // renders, so doing nothing is correct — never leave the page unstyled over a theme.
    document.documentElement.setAttribute('data-theme', 'dark');
  }
})();
