/**
 * Generated by Loom — do not edit. A resync overwrites this file.
 * Keep changes at the call site (className, a prop, a wrapper); those survive a resync.
 */
'use client';

import { createContext, useContext, useEffect, useState, type ReactNode } from 'react';

type Theme = 'light' | 'dark' | 'system';

interface ThemeContextValue {
  theme: Theme;
  resolved: 'light' | 'dark';
  setTheme: (theme: Theme) => void;
}

const ThemeContext = createContext<ThemeContextValue | undefined>(undefined);

const STORAGE_KEY = 'theme';
const DEFAULT_THEME: Theme = 'dark';

function getSystemTheme(): 'light' | 'dark' {
  if (typeof window === 'undefined') return 'dark';
  return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
}

function resolveTheme(theme: Theme): 'light' | 'dark' {
  return theme === 'system' ? getSystemTheme() : theme;
}

/** Read the stored choice. Guarded: localStorage throws rather than returning null in a
 *  private window with site data blocked, and an unguarded read here takes the provider
 *  down with it. theme-init.js guards the same call for the same reason. */
function readStored(): Theme | null {
  try {
    const saved = localStorage.getItem(STORAGE_KEY);
    return saved === 'light' || saved === 'dark' || saved === 'system' ? saved : null;
  } catch {
    return null;
  }
}

/** Write the resolved mode to the document, and only if it is not already there.
 *  colorScheme rides along: it is what makes the UA paint form controls, the scrollbar
 *  gutter and the canvas to match, and no Loom stylesheet sets it. */
function apply(r: 'light' | 'dark') {
  const el = document.documentElement;
  if (el.getAttribute('data-theme') !== r) el.setAttribute('data-theme', r);
  el.style.colorScheme = r;
}

export function ThemeProvider({ children }: { children: ReactNode }) {
  const [theme, setThemeState] = useState<Theme>(DEFAULT_THEME);
  const [resolved, setResolved] = useState<'light' | 'dark'>('dark');

  // Adopt what is stored. The apply() is a no-op when theme-init.js already set the
  // attribute to the same value, which is the whole point of the split.
  useEffect(() => {
    const next = readStored() ?? DEFAULT_THEME;
    const r = resolveTheme(next);
    setThemeState(next);
    setResolved(r);
    apply(r);
  }, []);

  // Only while following the system. Nothing here runs on mount for a fixed theme, which
  // is what stops this effect stamping DEFAULT_THEME over the first frame.
  useEffect(() => {
    if (theme !== 'system') return;
    const mq = window.matchMedia('(prefers-color-scheme: dark)');
    const handler = () => {
      const sys = getSystemTheme();
      setResolved(sys);
      apply(sys);
    };
    mq.addEventListener('change', handler);
    return () => mq.removeEventListener('change', handler);
  }, [theme]);

  // The DOM write for a deliberate change lives here rather than in an effect, so a
  // toggle takes effect in the same tick the user clicked.
  const setTheme = (t: Theme) => {
    const r = resolveTheme(t);
    setThemeState(t);
    setResolved(r);
    apply(r);
    try {
      localStorage.setItem(STORAGE_KEY, t);
    } catch {
      // Storage blocked. The theme still changes for this session; it just will not
      // survive a reload, which is better than throwing out of a click handler.
    }
  };

  return (
    <ThemeContext.Provider value={{ theme, resolved, setTheme }}>
      {children}
    </ThemeContext.Provider>
  );
}

export function useTheme() {
  const ctx = useContext(ThemeContext);
  if (!ctx) throw new Error('useTheme must be used within ThemeProvider');
  return ctx;
}
