#!/usr/bin/env node
/**
 * provenance.test.js — check that sync.js can always name the Loom it is delivering.
 *
 *   node scripts/provenance.test.js
 *
 * Weighted toward the cases that go wrong silently. A provenance string that is
 * right when everything is normal proves little; the failure worth catching is
 * `undefined` or a clean-looking hash stamped into ninety delivered files from a
 * tree that was not clean.
 *
 * Exits 1 if any case is wrong.
 */
const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { execFileSync } = require('child_process');

const { provenance, stamp } = require('./sync.js');

const COMPONENT_BANNER = [
  '/**',
  ' * Generated by Loom — do not edit. A resync overwrites this file.',
  ' * Keep changes at the call site (className, a prop, a wrapper); those survive a resync.',
  ' */',
].join('\n');

const STYLESHEET_BANNER = [
  '/**',
  ' * tokens.css — generated, do not edit. Regenerate from spec/config/.',
  ' */',
].join('\n');

const STYLESHEET_BANNER_NO_ADVICE = [
  '/**',
  ' * tokens.css — generated, do not edit.',
  ' */',
].join('\n');

let failures = 0;

function check(label, fn) {
  try {
    fn();
    console.log(`  ok    ${label}`);
  } catch (error) {
    failures += 1;
    console.log(`  FAIL  ${label}`);
    console.log(`        ${error.message.split('\n')[0]}`);
  }
}

/** Make a throwaway repo with a commit in it, and return its path. */
function repoWith(files) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'loom-prov-'));
  for (const [name, body] of Object.entries(files)) {
    fs.writeFileSync(path.join(root, name), body);
  }
  const git = (...args) => execFileSync('git', ['-C', root, ...args], { stdio: 'ignore' });
  git('init', '-q');
  git('add', '-A');
  git('-c', 'user.name=t', '-c', 'user.email=t@t', 'commit', '-q', '--no-verify', '-m', 'x');
  return root;
}

console.log('provenance');

check("names Loom's own version and a short hash", () => {
  assert.match(provenance(), /^\d+\.\d+\.\d+ \([0-9a-f]{7,}(-dirty)?\)$/);
});

check('marks a dirty producing tree', () => {
  const root = repoWith({ 'package.json': '{"version":"9.9.9"}', 'a.txt': 'one' });
  assert.strictEqual(provenance(root), '9.9.9 (' + short(root) + ')');
  fs.writeFileSync(path.join(root, 'a.txt'), 'two');
  assert.strictEqual(provenance(root), '9.9.9 (' + short(root) + '-dirty)');
});

check('names an unknown commit rather than undefined outside a repo', () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'loom-prov-'));
  fs.writeFileSync(path.join(root, 'package.json'), '{"version":"1.2.3"}');
  assert.strictEqual(provenance(root), '1.2.3 (unknown-commit)');
});

check('names an unknown version rather than undefined without a package.json', () => {
  const root = repoWith({ 'a.txt': 'one' });
  assert.strictEqual(provenance(root), 'unknown-version (' + short(root) + ')');
});

check('never returns undefined in any part of the string', () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'loom-prov-'));
  assert.doesNotMatch(provenance(root), /undefined/);
});

console.log('stamp');

check('stamps the component banner', () => {
  const out = stamp(COMPONENT_BANNER, '3.0.0 (abc1234)');
  assert.match(out, /Generated by Loom 3\.0\.0 \(abc1234\) — do not edit\./);
});

check('stamps the stylesheet banner', () => {
  const out = stamp(STYLESHEET_BANNER, '3.0.0 (abc1234)');
  assert.match(out, /tokens\.css — generated by Loom 3\.0\.0 \(abc1234\), do not edit\./);
});

// theme-init.js phrases it with a semicolon. An em-dash-only rule missed it, and
// the first real sync refused rather than delivering it unattributed.
check('stamps the theme-init banner, which words it differently', () => {
  const banner = '/**\n * your stylesheet. Generated by Loom; do not edit here.\n */\n';
  assert.match(stamp(banner, '3.0.0 (abc1234)'), /Generated by Loom 3\.0\.0 \(abc1234\); do not edit here\./);
});

// "Regenerate from spec/config/" is true in Loom and false in a consumer, and the
// nearest spec/config/ that exists emits Loom's brand rather than theirs.
check('redirects the stylesheet regenerate advice to the consumer command', () => {
  const out = stamp(STYLESHEET_BANNER, '3.0.0 (abc1234)');
  assert.match(out, /Regenerate with: npm run loom:sync/);
  assert.doesNotMatch(out, /spec\/config/);
});

check('leaves a component banner untouched by that redirect', () => {
  const body = `${COMPONENT_BANNER}\n// Regenerate from spec/config/.\n`;
  assert.match(stamp(body, '3.0.0 (abc1234)'), /Regenerate from spec\/config\/\./);
});

check('refuses a stylesheet banner whose regenerate line went missing', () => {
  assert.throws(() => stamp(STYLESHEET_BANNER_NO_ADVICE, '3.0.0 (abc1234)'));
});

check('leaves the rest of the file alone', () => {
  const body = `${COMPONENT_BANNER}\nexport const x = 1;\n`;
  assert.ok(stamp(body, '3.0.0 (abc1234)').endsWith('export const x = 1;\n'));
});

// The failure this whole change exists to prevent, one level up: a rewrite that
// matches nothing reports exactly like one that worked.
check('refuses a file with no generated header', () => {
  assert.throws(() => stamp('export const x = 1;\n', '3.0.0 (abc1234)'));
});

check('refuses a banner whose wording drifted', () => {
  assert.throws(() => stamp('/**\n * Made by Loom, do not edit.\n */\n', '3.0.0 (abc1234)'));
});

/** The short hash git itself would print for a repo, so the test does not reimplement it. */
function short(root) {
  return execFileSync('git', ['-C', root, 'rev-parse', '--short', 'HEAD'], {
    encoding: 'utf8',
  }).trim();
}

console.log(failures ? 'failed' : 'pass');
process.exit(failures ? 1 : 0);
